site_name: ARGO API AUTHN[V1]
site_url:
repo_url: https://github.com/ARGOeu/argo-api-authn
site_description: ARGO is a lightweight service for Service Level Monitoring designed for medium and large sized e-Infrastructures.
remote_branch: devel
copyright: Copyright © 2018 GRNET S.A.

pages:
#- Basic Information:
 #   - Overview and Introduction:
 #   - API flow:
 #   - Authentication & Authorization:
#- How to Guides:
- API & References:
#    - API Basic Information:
#    - API Authentication:
    - API Bindings: api_bindings.md
    - API Service Types: api_service_types.md
    - Deprecated API Auth Methods: api_auth_methods.md
    - API Auth Methods: api_authmethods.md
    - API Certificate Functionality: auth_certificate.md
    - API Error Messages: api_errors.md
theme: readthedocs
